using System;
using UnityEditor;
using UnityEngine;

namespace Editor
{
    public class RenderToCubeMap : EditorWindow
    {
        private GameObject obj;
        private Cubemap cubemap;
        [MenuItem("GenerateTexture/Generate CubeMap")]
        private static void OpenWin()
        {
            EditorWindow.GetWindow<RenderToCubeMap>("Generating CubeMap Window").Show();
        }

        private void OnGUI()
        {
            // bind object of generating CubeMap
            GUILayout.BeginHorizontal();
            GUILayout.Label("GameObject In Scene: ");
            obj = EditorGUILayout.ObjectField(obj, typeof(GameObject), true) as GameObject;
            GUILayout.EndHorizontal();
            
            // bind CubeMap to contain the generating result
            GUILayout.BeginHorizontal();
            GUILayout.Label("CubeMap Container: ");
            cubemap = EditorGUILayout.ObjectField(cubemap, typeof(Cubemap), false) as Cubemap;
            GUILayout.EndHorizontal();
            
            if (GUILayout.Button("Generate CubeMap"))
            {
                if (obj is null || cubemap is null)
                {
                    EditorUtility.DisplayDialog("Generating Error",
                        "Please binding GameObject and CubeMap before generating", "Sure");
                    return;
                }
                
                // generate a temp object to generate Cubemap
                // Cubemap need to be generated by a Camera Component
                GameObject temp = new GameObject("Temp Obj");
                // Set temp position to Selected GameObject(obj)
                temp.transform.position = obj.transform.position;
                Camera camera = temp.AddComponent<Camera>();
                bool isSuccess = camera.RenderToCubemap(cubemap);
                if (isSuccess == false)
                    EditorUtility.DisplayDialog("Generating Failed", "Error happened in Generating Process", "Sure");
                else
                    EditorUtility.DisplayDialog("Generating Success", "Generating Success", "Sure");
                                        
                DestroyImmediate(temp);

            }
        }
    }
}
